[project]
name = "video-ads"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphon-client>=0.5.0",
    "moviepy>=2.2.1",
    "pydantic>=2.0.0",
]
